### ISSUE TITLE
Option to "bake" an AutoLayer?

### ISSUE THREAD

**Issue by profexorgeek** [deepnight/led#182]
I have been testing this tool heavily for production level design. As an artist I love the time savings of auto-tiles and rules. But I also want to retain artistic control of key areas. My desired workflow would be:

1. Create an autolayer with rules
1. Quickly lay out large levels
1. "Bake" the autolayer (convert it or duplicate it into a Tiled layer)
1. Hand edit key areas, replacing and tweaking tiles

Perhaps the intended pattern is to create a tile layer above the autolayer and just overlay the autotiles?

**Comment by deepnight** [comment]
I understand your approach, and yes, it's definitely a nice idea to be able to bake an auto layer to a grid layer. I'll see how it could be done :) 

Anyway, it might be interesting to keep the dynamic rule system (in case you decide to update them to add more variety). The way I personally work is having AutoLayers to do all the base skinning, and have multiple traditional Tile layers to add custom details by hand. 

In the 0.5.x milestone, I plan to add support for *stackable* tiles per layers which will be a huge time-saver because it'll remove the need for having many separate layers to stack details (see #179)
